Add create product feature
ahung1709/Aaron-Hung-IS24-full-stack-competition-req97073 pull request #1
Opened 2023-10-02 18:17 UTC by ahung1709

This is for adding logic for creating product feature

2023-10-02 18:27 UTC, evert requested changes

2023-10-02 18:27 UTC, evert commented on controllers/products.js
> +    // }
Remove dead code

2023-10-02 18:27 UTC, evert commented on data/products.json
> +[{"productId":"Prplw8","productName":"Product10e","productOwnerName":"Anthony Shanthan","Developers":["Arthur Riches","Luna Kalay","Michael Grams"],"scrumMasterName":"Aidan McGhie","startDate":"2022/
This is your database, and this will always be different for different people, so it should not get committed and instead added to `.gitignore`

2023-10-02 18:27 UTC, evert commented on routes/api/products.js
> +// console.log("inside router before findByScrumMasterName")
Remove all debug code

2023-10-02 18:27 UTC, evert commented on services/product.js
> +    console.log("update: products", products)
Debug code!

2023-10-02 18:27 UTC, evert commented on services/product.js
> +    } while (products.reduce( (acc, product) => acc || (product.productId === pId), false));
instead of `reduce`, you probably want to use `find`

2023-10-02 18:27 UTC, evert commented on services/product.js
> +function createProduct(productId = "", productName= "", ownerName= "", arrDevelopers = [], scrumMasterName = "", startDate = "", methodology = "") {
Two things here:

1. I think it would be good to pass the values as an object, and not individual arguments.
2. All the arguments have a default value, is that really what you want? If an empty string for for example `startDate` is not valid, then this function allows invalid products to be created. It might be better to throw an error when something is missing.

2023-10-02 18:27 UTC, evert commented on services/product.js
> +    const methodology = product.methodology ? product.methodology : ""
Do you really want  all these variables to default to empty strings and arrays? Maybe it's better to throw an error if something is missing.

2023-10-08 07:29 UTC, ahung1709 commented on controllers/products.js
> +    // }
done

2023-10-08 07:31 UTC, ahung1709 commented on data/products.json
> +[{"productId":"Prplw8","productName":"Product10e","productOwnerName":"Anthony Shanthan","Developers":["Arthur Riches","Luna Kalay","Michael Grams"],"scrumMasterName":"Aidan McGhie","startDate":"2022/
.gitignore is updated, but Adding data/products.json to gitignore doesn’t seem to work

2023-10-08 07:31 UTC, ahung1709 commented on routes/api/products.js
> +// console.log("inside router before findByScrumMasterName")
done

2023-10-08 07:32 UTC, ahung1709 commented on services/product.js
> +    console.log("update: products", products)
done - debug code is removed

2023-10-08 07:33 UTC, ahung1709 commented on services/product.js
> +    } while (products.reduce( (acc, product) => acc || (product.productId === pId), false));
done - updated to use **find**

2023-10-08 07:36 UTC, ahung1709 commented on services/product.js
> +function createProduct(productId = "", productName= "", ownerName= "", arrDevelopers = [], scrumMasterName = "", startDate = "", methodology = "") {
1. Done, but I have a question: This is a helper function.  If I pass values as an object, the keys used in the helper function will need to agree with the keys of the object given by the user function.  Would it be better to leave values as input?
2. Done, but see also comment in next suggested change

2023-10-08 07:37 UTC, ahung1709 commented on services/product.js
> +    const methodology = product.methodology ? product.methodology : ""
done.
Just a thought: Do we need to check for errors in input in both the helper function and the user function?  Is there any way to simplify the code so I am not repeating the logic in both functions?

2023-10-16 01:07 UTC, ahung1709 commented on services/product.js
> +    const methodology = product.methodology ? product.methodology : ""
Done - validateProduct function is created for validation of product, so checking errors is only done in one place.

2023-10-16 18:20 UTC, evert approved these changes

2023-10-16 18:20 UTC, evert commented on data/products.json
> +[{"productId":"Prplw8","productName":"Product10","productOwnerName":"Anthony Shanthan","Developers":["Arthur Riches","Luna Kalay","Michael Grams"],"scrumMasterName":"Aidan McGhie","startDate":"2022/1
This file is now in `.gitignore` but i think it still needs to be removed from git.

2023-10-16 18:20 UTC, evert commented on services/product.js
> +    }
```suggestion

    if (!product.productId) {
        throw new Error ("Product ID was missing!");
    }
    if (!product.productName) {
        throw new Error ("Product name was missing!");
    }
    if (!product.productOwnerName) {
        throw new Error ("Owner name was missing!");
    }
    if (!Array.isArray(product.developers) || !product.developers.filter(n => n).length) {
        throw new Error ("Developers is not an array, is an empty array!!");
    }
    if (!product.crumMasterName) {
        throw new Error ("Scrum master name was missing!");
    }
    if (!product.startDate) {
        throw new Error ("Start date was missing!");
    }
    if (!product.methodology) {
        throw new Error ("Methodology was missing!");
    }
    return product;
}
```

2023-10-16 18:20 UTC, evert commented on services/product.js
> +    }
Maybe the name of this function can now be 'validateProduct'.

2023-10-16 18:20 UTC, evert commented on services/product.js
> +    const methodology = product.methodology ? product.methodology : ""
No, the `createProduct` function should be called `validateProduct` and you can re-use this new validation function everywhere you need it

2023-10-16 18:20 UTC, evert commented on services/product.js
> +    }
```suggestion
function validateProduct(product) { 
    if (!product.productId) {
        throw new Error ("Product ID was missing!");
    }
    if (!product.productName) {
        throw new Error ("Product name was missing!");
    }
    if (!product.productOwnerName) {
        throw new Error ("Owner name was missing!");
    }
    if (!Array.isArray(product.Developers) || !product.Developers.filter(n => n).length) {
        throw new Error ("Developers is not an array, or is an empty array!!");
    }
    if (!product.scrumMasterName) {
        throw new Error ("Scrum master name was missing!");
    }
    if (!product.startDate) {
        throw new Error ("Start date was missing!");
    }
    if (!product.methodology) {
        throw new Error ("Methodology was missing!");
    } 
     return true;
}
```

2023-10-16 18:45 UTC, merged